### ISSUE TITLE
not working in nuxt

### ISSUE THREAD

**Issue by kunaldodiya** [buhrmi/nuxt-pouch#1]
I have tried it in vue2.0 worked well, but then i installed it nuxtjs and showing errors :)

```
index-browser.es.js:1365 Uncaught (in promise) TypeError: __webpack_require__.i(...) is not a function
    at PouchDB$5.<anonymous> (http://127.0.0.1:3000/_nuxt/vendor.bundle.bce87d3573e2da2c09e4.js:22335:95)
    at http://127.0.0.1:3000/_nuxt/vendor.bundle.bce87d3573e2da2c09e4.js:8840:21
    at Promise (<anonymous>)
    at PouchDB$5.<anonymous> (http://127.0.0.1:3000/_nuxt/vendor.bundle.bce87d3573e2da2c09e4.js:8827:19)
    at PouchDB$5.find (http://127.0.0.1:3000/_nuxt/vendor.bundle.bce87d3573e2da2c09e4.js:10557:18)
    at PouchDB$5.liveFind (http://127.0.0.1:3000/_nuxt/vendor.bundle.bce87d3573e2da2c09e4.js:22507:18)
    at VueComponent.vm.$watch.immediate (http://127.0.0.1:3000/_nuxt/vendor.bundle.bce87d3573e2da2c09e4.js:36433:35)
    at VueComponent.Vue.$watch (http://127.0.0.1:3000/_nuxt/vendor.bundle.bce87d3573e2da2c09e4.js:3227:10)
    at http://127.0.0.1:3000/_nuxt/vendor.bundle.bce87d3573e2da2c09e4.js:36402:12
    at Array.map (native)
```

i dont know what to do please help

**Comment by kunaldodiya** [comment]
here is repository, you can download and reproduced the error :) https://github.com/kunaldodiya/ssx

**Comment by buhrmi** [comment]
Tried to view your repo but I can't find it. please re-open a new issue if you're still having trouble.
